name: Algolia update index

on:
  workflow_dispatch:

jobs:
  job_algolia:
    name: Algolia updates
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
      API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Docker image
      run: |
        apt install jq -y
        cat algolia_config.json | jq -r tostring

# docker run -it -e APPLICATION_ID=$APPLICATION_ID -e API_KEY=$API_KEY -e "CONFIG=$(cat algolia_config.json | jq -r tostring)" algolia/docsearch-scraper