name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORGANIZATION_NAME: ${{ secrets.ORGANIZATION_NAME }}
      REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
      SITE_TITLE: ${{ secrets.SITE_TITLE }}
      SITE_URL: ${{ secrets.SITE_URL }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run typecheck
      - run: npm run format:check
      - run: npm run build